version: "3.3"

services:
  frontend-app:
    stdin_open: true
    build: ./frontend
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn start"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend: